### ISSUE TITLE
Error when no colouring selected

### ISSUE THREAD

**Issue by CrystalGrower** [CrystalGrowerOrg/cgaspects#96]
When you opt for no colouring in the CG simulations then the simulation_parameters.txt does not contain any crystal size information. Then there is an error message as shown below which, in this case, is not an error.

Couldn't find any *simulation_parameters.txt files. Please make sure you have selected theCrystalGrower output directory from the simulation(s).

**Comment by AJen01** [comment]
I have addressed this in the above commit, if you could confirm that it is fixed, we can close this issue.
